[package]
name = "astar"
version = "0.1.0"
edition = "2021"

[dependencies]
priority-queue = "1.0.2"
png = "0.17.3"
rand = { version = "0.8", features = ["small_rng"] }

[profile.release]
debug = true
